"""Add forensic evidence tables

Revision ID: d45710dd47b5
Revises: 
Create Date: 2026-01-17 06:28:05.495628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45710dd47b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_file_hash'), 'audio_files', ['file_hash'], unique=True)
    op.create_table('custody_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_uuid', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('timestamp_rfc3161', sa.Text(), nullable=True),
    sa.Column('custodian_id', sa.String(length=100), nullable=True),
    sa.Column('custodian_name', sa.String(length=255), nullable=True),
    sa.Column('custodian_role', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('facility', sa.String(length=255), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('digital_signature', sa.Text(), nullable=True),
    sa.Column('transfer_reason', sa.Text(), nullable=True),
    sa.Column('transfer_method', sa.String(length=50), nullable=True),
    sa.Column('received_by', sa.String(length=255), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('evidence_number', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('witnesses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custody_log_asset_uuid'), 'custody_log', ['asset_uuid'], unique=False)
    op.create_index(op.f('ix_custody_log_case_number'), 'custody_log', ['case_number'], unique=False)
    op.create_index(op.f('ix_custody_log_evidence_number'), 'custody_log', ['evidence_number'], unique=False)
    op.create_table('forensic_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_uuid', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('evidence_number', sa.String(length=100), nullable=False),
    sa.Column('collection_date', sa.DateTime(), nullable=False),
    sa.Column('collector_id', sa.String(length=100), nullable=True),
    sa.Column('collector_name', sa.String(length=255), nullable=True),
    sa.Column('collection_method', sa.String(length=100), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('current_custodian', sa.String(length=255), nullable=True),
    sa.Column('digital_signature', sa.Text(), nullable=True),
    sa.Column('timestamp_rfc3161', sa.Text(), nullable=True),
    sa.Column('analysis_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forensic_evidence_asset_uuid'), 'forensic_evidence', ['asset_uuid'], unique=True)
    op.create_index(op.f('ix_forensic_evidence_case_number'), 'forensic_evidence', ['case_number'], unique=False)
    op.create_index(op.f('ix_forensic_evidence_evidence_number'), 'forensic_evidence', ['evidence_number'], unique=True)
    op.create_index(op.f('ix_forensic_evidence_file_hash'), 'forensic_evidence', ['file_hash'], unique=True)
    op.create_table('method_validation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method_name', sa.String(length=255), nullable=False),
    sa.Column('method_version', sa.String(length=50), nullable=False),
    sa.Column('method_type', sa.String(length=100), nullable=False),
    sa.Column('validation_date', sa.DateTime(), nullable=False),
    sa.Column('validator_id', sa.String(length=100), nullable=False),
    sa.Column('validator_name', sa.String(length=255), nullable=False),
    sa.Column('documented_in_sop', sa.Boolean(), nullable=False),
    sa.Column('validated_with_reference', sa.Boolean(), nullable=False),
    sa.Column('uncertainty_calculated', sa.Boolean(), nullable=False),
    sa.Column('detection_limit_determined', sa.Boolean(), nullable=False),
    sa.Column('selectivity_verified', sa.Boolean(), nullable=False),
    sa.Column('robustness_tested', sa.Boolean(), nullable=False),
    sa.Column('bias_verified', sa.Boolean(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('confidence_interval_lower', sa.Float(), nullable=True),
    sa.Column('confidence_interval_upper', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('reference_document_path', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('corrective_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_verification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('tool_version', sa.String(length=100), nullable=False),
    sa.Column('tool_vendor', sa.String(length=255), nullable=True),
    sa.Column('tool_type', sa.String(length=100), nullable=False),
    sa.Column('verification_date', sa.DateTime(), nullable=False),
    sa.Column('verifier_id', sa.String(length=100), nullable=False),
    sa.Column('verifier_name', sa.String(length=255), nullable=False),
    sa.Column('calibration_date', sa.DateTime(), nullable=True),
    sa.Column('next_calibration_date', sa.DateTime(), nullable=True),
    sa.Column('calibration_certificate_number', sa.String(length=255), nullable=True),
    sa.Column('calibration_organization', sa.String(length=255), nullable=True),
    sa.Column('version_verified', sa.Boolean(), nullable=False),
    sa.Column('functionality_verified', sa.Boolean(), nullable=False),
    sa.Column('accuracy_verified', sa.Boolean(), nullable=False),
    sa.Column('reproducibility_verified', sa.Boolean(), nullable=False),
    sa.Column('license_valid', sa.Boolean(), nullable=False),
    sa.Column('test_case_count', sa.Integer(), nullable=True),
    sa.Column('passed_test_cases', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verification_report_path', sa.String(length=512), nullable=True),
    sa.Column('known_issues', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audio_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_segments')
    op.drop_table('transcripts')
    op.drop_table('tool_verification')
    op.drop_table('method_validation')
    op.drop_index(op.f('ix_forensic_evidence_file_hash'), table_name='forensic_evidence')
    op.drop_index(op.f('ix_forensic_evidence_evidence_number'), table_name='forensic_evidence')
    op.drop_index(op.f('ix_forensic_evidence_case_number'), table_name='forensic_evidence')
    op.drop_index(op.f('ix_forensic_evidence_asset_uuid'), table_name='forensic_evidence')
    op.drop_table('forensic_evidence')
    op.drop_index(op.f('ix_custody_log_evidence_number'), table_name='custody_log')
    op.drop_index(op.f('ix_custody_log_case_number'), table_name='custody_log')
    op.drop_index(op.f('ix_custody_log_asset_uuid'), table_name='custody_log')
    op.drop_table('custody_log')
    op.drop_index(op.f('ix_audio_files_file_hash'), table_name='audio_files')
    op.drop_table('audio_files')
    # ### end Alembic commands ###
